FROM registry.access.redhat.com/ubi9/python-311:1-77.1729767833

USER root

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash && \
    dnf install -y git-lfs

RUN git clone https://huggingface.co/instructlab/granite-7b-lab
