kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csp-managed-disk
  namespace: triton-profiling
  labels:
    app: triton
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Block
  resources:
    requests:
      storage: 40Gi
