kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csp-managed-disk
  namespace: triton-profiling
  labels:
    author: grpereir
    app: triton-profiling
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
