apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: granite-7b-lab-pvc
  namespace: triton-profiling
  labels:
    author: grpereir
    app: triton-profiling
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
    limits:
      storage: 40Gi
  storageClassName: nfs-csi
  volumeMode: Filesystem
