apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: granite-7b-lab
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/grpereir/granite-7b-lab:latest
