apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
  namespace: triton-profiling
spec:
  containers:
  - name: pvc-inspector-container
    image: busybox  # A lightweight image with basic file system utilities
    command: ["sleep", "3600"]  # Keeps the pod running so you can exec into it
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: csp-managed-disk
  restartPolicy: Never
