kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csp-managed-disk
  namespace: triton
  labels:
    app: triton
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
