apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-metrics-collector-triton-profiling
  namespace: triton-profiling
  labels:
    app: triton-profiling
  annotations:
    openshift.io/required-scc: nvidia-devtools-sidecar-injector
spec:
  selector:
    matchLabels:
      app: triton-profiling
  template:
    metadata:
      labels:
        app: triton-profiling
      annotations:
        openshift.io/required-scc: nvidia-devtools-sidecar-injector
    spec:
      serviceAccountName: nvidia-devtools-sidecar-injector
      containers:
      - name: gpu-metrics-ubuntu-container
        image: ubuntu:22.04
        command: ["sleep", "infinity"]
        securityContext:
          privileged: true
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
